"""OpenAPI contract validation tests - prevent drift and ensure contract stability."""

import hashlib
import json
from pathlib import Path
from typing import Any

import pytest


BACKEND_DIR = Path(__file__).resolve().parent.parent
OPENAPI_PATH = BACKEND_DIR / "openapi.json"


def load_openapi_schema() -> dict[str, Any]:
    """Load the OpenAPI schema from disk."""
    with open(OPENAPI_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def compute_schema_hash(schema: dict[str, Any]) -> str:
    """Compute deterministic SHA256 hash of schema."""
    # Serialize with sorted keys for consistency
    schema_json = json.dumps(schema, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(schema_json.encode("utf-8")).hexdigest()


class TestOpenAPIContractStability:
    """Tests to prevent unintended OpenAPI contract drift."""

    def test_openapi_file_exists(self):
        """Ensure the OpenAPI schema file exists."""
        assert OPENAPI_PATH.exists(), (
            f"OpenAPI schema not found at {OPENAPI_PATH}. "
            "Run: python3 backend/scripts/generate_openapi.py"
        )

    def test_openapi_is_valid_json(self):
        """Ensure the OpenAPI file contains valid JSON."""
        schema = load_openapi_schema()
        assert isinstance(schema, dict), "OpenAPI schema must be a JSON object"
        assert "openapi" in schema, "Schema must have 'openapi' field"
        assert "info" in schema, "Schema must have 'info' field"
        assert "paths" in schema, "Schema must have 'paths' field"

    def test_operation_id_uniqueness(self):
        """Ensure all operationIds are unique across the API."""
        schema = load_openapi_schema()
        operation_ids: dict[str, list[str]] = {}
        
        for path, path_item in schema.get("paths", {}).items():
            for method in ["get", "post", "put", "patch", "delete", "options", "head"]:
                if method not in path_item:
                    continue
                
                operation = path_item[method]
                if not isinstance(operation, dict):
                    continue
                
                operation_id = operation.get("operationId")
                if not operation_id:
                    pytest.fail(
                        f"Missing operationId for {method.upper()} {path}"
                    )
                
                if operation_id not in operation_ids:
                    operation_ids[operation_id] = []
                operation_ids[operation_id].append(f"{method.upper()} {path}")
        
        # Check for duplicates
        duplicates = {
            op_id: locations
            for op_id, locations in operation_ids.items()
            if len(locations) > 1
        }
        
        if duplicates:
            error_msg = "Duplicate operationId detected:\n"
            for op_id, locations in duplicates.items():
                error_msg += f"  {op_id}:\n"
                for loc in locations:
                    error_msg += f"    - {loc}\n"
            pytest.fail(error_msg)

    def test_operation_ids_stable(self):
        """Ensure operationIds follow stable naming conventions."""
        schema = load_openapi_schema()
        
        for path, path_item in schema.get("paths", {}).items():
            for method in ["get", "post", "put", "patch", "delete"]:
                if method not in path_item:
                    continue
                
                operation = path_item[method]
                if not isinstance(operation, dict):
                    continue
                
                operation_id = operation.get("operationId")
                if not operation_id:
                    continue
                
                # operationId should be meaningful and not autogenerated garbage
                assert len(operation_id) > 3, (
                    f"operationId too short for {method.upper()} {path}: {operation_id}"
                )
                
                # Should not contain special characters
                assert operation_id.replace("_", "").isalnum(), (
                    f"operationId contains special chars for {method.upper()} {path}: {operation_id}"
                )

    def test_security_schemes_defined(self):
        """Ensure all required security schemes are properly defined."""
        schema = load_openapi_schema()
        
        components = schema.get("components", {})
        security_schemes = components.get("securitySchemes", {})
        
        # Verify all required security schemes exist
        required_schemes = {
            "AdminJWT",
            "InternalAdminKey",
            "TenantApiKey",
            "WidgetToken"
        }
        
        defined_schemes = set(security_schemes.keys())
        missing = required_schemes - defined_schemes
        
        assert not missing, (
            f"Missing required security schemes: {missing}. "
            f"Found: {defined_schemes}"
        )
        
        # Verify each scheme has a description
        for scheme_name, scheme_def in security_schemes.items():
            assert "description" in scheme_def, (
                f"Security scheme '{scheme_name}' missing description"
            )
            assert len(scheme_def["description"]) > 20, (
                f"Security scheme '{scheme_name}' has too short description"
            )

    def test_security_scheme_descriptions_complete(self):
        """Ensure security scheme descriptions contain key information."""
        schema = load_openapi_schema()
        security_schemes = schema["components"]["securitySchemes"]
        
        # AdminJWT should mention duration and source
        admin_jwt = security_schemes["AdminJWT"]["description"]
        assert "15" in admin_jwt or "minute" in admin_jwt.lower(), (
            "AdminJWT description should mention token lifetime"
        )
        assert "login" in admin_jwt.lower(), (
            "AdminJWT description should mention login endpoint"
        )
        
        # InternalAdminKey should mention deprecation
        admin_key = security_schemes["InternalAdminKey"]["description"]
        assert "deprecated" in admin_key.lower() or "legacy" in admin_key.lower(), (
            "InternalAdminKey description should mention deprecation"
        )
        
        # TenantApiKey should warn about browser exposure
        tenant_key = security_schemes["TenantApiKey"]["description"]
        assert "never" in tenant_key.lower() or "browser" in tenant_key.lower(), (
            "TenantApiKey description should warn against browser exposure"
        )
        
        # WidgetToken should mention it's browser-safe
        widget_token = security_schemes["WidgetToken"]["description"]
        assert "browser" in widget_token.lower() or "safe" in widget_token.lower(), (
            "WidgetToken description should mention browser safety"
        )
        assert "10" in widget_token or "minute" in widget_token.lower(), (
            "WidgetToken description should mention token lifetime"
        )

    def test_schema_has_proper_structure(self):
        """Ensure OpenAPI schema has expected top-level structure."""
        schema = load_openapi_schema()
        
        # Required top-level fields
        assert "openapi" in schema
        assert schema["openapi"].startswith("3."), "Must be OpenAPI 3.x"
        
        assert "info" in schema
        assert "title" in schema["info"]
        assert "version" in schema["info"]
        
        assert "paths" in schema
        assert len(schema["paths"]) > 0, "Must have at least one path"
        
        assert "components" in schema
        assert "schemas" in schema["components"]
        assert "securitySchemes" in schema["components"]

    def test_no_undefined_refs(self):
        """Ensure all $ref references point to defined components."""
        schema = load_openapi_schema()
        components = schema.get("components", {})
        schemas = components.get("schemas", {})
        
        def collect_refs(obj: Any, refs: set[str]) -> None:
            """Recursively collect all $ref values."""
            if isinstance(obj, dict):
                if "$ref" in obj:
                    refs.add(obj["$ref"])
                for value in obj.values():
                    collect_refs(value, refs)
            elif isinstance(obj, list):
                for item in obj:
                    collect_refs(item, refs)
        
        all_refs: set[str] = set()
        collect_refs(schema, all_refs)
        
        # Verify all refs are defined
        undefined_refs = []
        for ref in all_refs:
            if ref.startswith("#/components/schemas/"):
                schema_name = ref.split("/")[-1]
                if schema_name not in schemas:
                    undefined_refs.append(ref)
        
        assert not undefined_refs, (
            f"Undefined schema references: {undefined_refs}"
        )

    def test_deterministic_output(self):
        """Ensure schema file has deterministic structure (sorted keys)."""
        with open(OPENAPI_PATH, "r", encoding="utf-8") as f:
            content = f.read()
        
        # Parse and re-serialize with sorted keys
        schema = json.loads(content)
        expected_content = json.dumps(
            schema, indent=2, ensure_ascii=False, sort_keys=True
        ) + "\n"
        
        assert content == expected_content, (
            "OpenAPI schema is not deterministically formatted. "
            "All keys should be sorted alphabetically."
        )

    def test_trailing_newline(self):
        """Ensure file ends with a trailing newline."""
        with open(OPENAPI_PATH, "rb") as f:
            f.seek(-1, 2)  # Seek to last byte
            last_byte = f.read(1)
        
        assert last_byte == b"\n", (
            "OpenAPI schema must end with a trailing newline"
        )


class TestOpenAPIContractDrift:
    """Tests to detect unintended changes to the API contract."""
    
    # Expected hash of openapi.json - update this when intentionally changing API
    # To update: run `python3 backend/scripts/generate_openapi.py` and copy new hash
    EXPECTED_SCHEMA_HASH = "6eb260da4d7c72cbf3dd7e87aba9e6f67e880695c68a1b36bf658baa53cb407d"
    
    def test_schema_hash_unchanged(self):
        """
        Detect unintended API contract changes by comparing schema hash.
        
        This test will fail if the OpenAPI schema changes in any way.
        
        To update after intentional API changes:
        1. Review the API changes carefully
        2. Run: python3 backend/scripts/generate_openapi.py
        3. Compute new hash: sha256sum backend/openapi.json
        4. Update EXPECTED_SCHEMA_HASH in this test
        5. Commit both the new openapi.json and this test file
        """
        schema = load_openapi_schema()
        current_hash = compute_schema_hash(schema)
        
        if current_hash != self.EXPECTED_SCHEMA_HASH:
            pytest.fail(
                f"\n"
                f"OpenAPI schema hash mismatch - API contract has changed!\n"
                f"Expected: {self.EXPECTED_SCHEMA_HASH}\n"
                f"Current:  {current_hash}\n"
                f"\n"
                f"If this change was intentional:\n"
                f"1. Review the API changes carefully\n"
                f"2. Regenerate schema: python3 backend/scripts/generate_openapi.py\n"
                f"3. Update EXPECTED_SCHEMA_HASH in tests/test_openapi_contract.py\n"
                f"4. Regenerate TypeScript clients\n"
                f"5. Commit all changes together\n"
            )

    def test_minimum_endpoint_count(self):
        """Ensure we haven't accidentally removed endpoints."""
        schema = load_openapi_schema()
        paths = schema.get("paths", {})
        
        # Count total operations
        operation_count = sum(
            1 for path_item in paths.values()
            for key in path_item.keys()
            if key in ["get", "post", "put", "patch", "delete"]
        )
        
        # We should have at least 25 operations (adjust based on your API)
        assert operation_count >= 25, (
            f"Expected at least 25 operations, found {operation_count}. "
            "Endpoints may have been accidentally removed."
        )

    def test_critical_endpoints_exist(self):
        """Ensure critical endpoints haven't been removed."""
        schema = load_openapi_schema()
        paths = schema.get("paths", {})
        
        # Define critical endpoints that must always exist
        critical_endpoints = [
            "/health",
            "/api/admin/auth/login",
            "/api/chat",
            "/api/knowledge-bases",
            "/api/widget/bootstrap",
        ]
        
        missing = [ep for ep in critical_endpoints if ep not in paths]
        
        assert not missing, (
            f"Critical endpoints missing: {missing}"
        )
