/** Supported placement of the launcher and panel. */
export type WidgetPosition = 'left' | 'right';

/** Supported visual modes returned by the trusted bootstrap API. */
export type WidgetAppearance = 'light' | 'dark';

/** Mock scenarios are available only for local development and tests. */
export type MockScenario =
  | 'happy-path'
  | 'slow-response'
  | 'error-response'
  | 'stream-error-midway';

/** Brand colours returned by the trusted bootstrap API. */
export interface ThemeTokens {
  primary: string;
  onPrimary: string;
  launcherBg: string;
  headerBg: string;
  userBubbleBg: string;
}

/** Local-only presentation overrides for the explicit mock transport. */
export interface MockWidgetConfig {
  displayName?: string;
  welcomeMessage?: string;
  theme?: Partial<ThemeTokens>;
  position?: WidgetPosition;
  appearance?: WidgetAppearance;
}

/**
 * Public embed configuration supplied by the customer website.
 *
 * A live embed deliberately accepts only the opaque public Widget ID and the
 * API origin. Agent identity, greeting, position and colours are resolved by
 * the origin-authorized bootstrap endpoint and cannot be selected here.
 */
export interface WidgetConfig {
  /** Opaque public identifier generated by the Admin Widget API. */
  widgetId?: string;

  /** API origin, for example https://ai.travel-x.online. */
  serverUrl?: string;

  /** Live HTTP is the default. Mock must be selected explicitly. */
  transport?: 'http' | 'mock';

  /** Local-only mock scenario. Ignored by the live HTTP transport. */
  mockScenario?: MockScenario;

  /** Local-only mock presentation. Ignored by the live HTTP transport. */
  mock?: MockWidgetConfig;

  /** BCP-47 language tag used for widget chrome. */
  language?: string;

  /** Explicit text direction, or automatic detection from the host page. */
  direction?: 'ltr' | 'rtl' | 'auto';

  /** Accessible label on the launcher button. */
  launcherLabel?: string;

  /** Shadow DOM encapsulation mode. Defaults to open for supportability. */
  shadowMode?: 'open' | 'closed';
}

/** Trusted presentation returned after a successful Widget bootstrap. */
export interface RuntimeWidgetConfig {
  displayName: string;
  welcomeMessage: string;
  theme: ThemeTokens;
  position: WidgetPosition;
  appearance: WidgetAppearance;
}

/** Fully validated configuration consumed by the widget runtime. */
export interface ResolvedConfig extends RuntimeWidgetConfig {
  widgetId: string;
  serverUrl: string;
  transport: 'http' | 'mock';
  mockScenario: MockScenario;
  language: string;
  direction: 'ltr' | 'rtl' | 'auto';
  launcherLabel: string;
  shadowMode: 'open' | 'closed';
}
